/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HabilidadGrupo = {
  _id: string;
  _type: "habilidadGrupo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombreGrupo?: string;
  habilidades?: Array<string>;
  orden?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Proyecto = {
  _id: string;
  _type: "proyecto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  descripcion?: string;
  imagen?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  etiquetaVisual?: string;
  herramientas?: Array<string>;
  destacado?: boolean;
  orden?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Experiencia = {
  _id: string;
  _type: "experiencia";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  empresa?: string;
  cargo?: string;
  fechaInicio?: string;
  fechaFin?: string;
  actual?: boolean;
  bullets?: Array<string>;
  orden?: number;
};

export type Perfil = {
  _id: string;
  _type: "perfil";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre?: string;
  rol?: string;
  bio?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  telefono?: string;
  linkedin?: string;
  ubicacion?: string;
  stats?: Array<{
    numero?: string;
    etiqueta?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | HabilidadGrupo
  | SanityImageAssetReference
  | Proyecto
  | SanityImageCrop
  | SanityImageHotspot
  | Experiencia
  | Perfil
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/app/page.tsx
// Variable: PERFIL_QUERY
// Query: *[_type == "perfil"][0]{  _id, nombre, rol, bio, foto, email, telefono, linkedin, ubicacion,  stats[]{ numero, etiqueta }}
export type PERFIL_QUERY_RESULT = {
  _id: string;
  nombre: string | null;
  rol: string | null;
  bio: string | null;
  foto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  email: string | null;
  telefono: string | null;
  linkedin: string | null;
  ubicacion: string | null;
  stats: Array<{
    numero: string | null;
    etiqueta: string | null;
  }> | null;
} | null;

// Source: ../web/src/app/page.tsx
// Variable: PROYECTOS_QUERY
// Query: *[_type == "proyecto"] | order(orden asc, _createdAt asc){  _id, titulo, descripcion, imagen, etiquetaVisual, herramientas, destacado}
export type PROYECTOS_QUERY_RESULT = Array<{
  _id: string;
  titulo: string | null;
  descripcion: string | null;
  imagen: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  etiquetaVisual: string | null;
  herramientas: Array<string> | null;
  destacado: boolean | null;
}>;

// Source: ../web/src/app/page.tsx
// Variable: EXPERIENCIA_QUERY
// Query: *[_type == "experiencia"] | order(orden asc, _createdAt asc){  _id, empresa, cargo, fechaInicio, fechaFin, actual, bullets}
export type EXPERIENCIA_QUERY_RESULT = Array<{
  _id: string;
  empresa: string | null;
  cargo: string | null;
  fechaInicio: string | null;
  fechaFin: string | null;
  actual: boolean | null;
  bullets: Array<string> | null;
}>;

// Source: ../web/src/app/page.tsx
// Variable: HABILIDADES_QUERY
// Query: *[_type == "habilidadGrupo"] | order(orden asc, _createdAt asc){  _id, nombreGrupo, habilidades}
export type HABILIDADES_QUERY_RESULT = Array<{
  _id: string;
  nombreGrupo: string | null;
  habilidades: Array<string> | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "perfil"][0]{\n  _id, nombre, rol, bio, foto, email, telefono, linkedin, ubicacion,\n  stats[]{ numero, etiqueta }\n}': PERFIL_QUERY_RESULT;
    '*[_type == "proyecto"] | order(orden asc, _createdAt asc){\n  _id, titulo, descripcion, imagen, etiquetaVisual, herramientas, destacado\n}': PROYECTOS_QUERY_RESULT;
    '*[_type == "experiencia"] | order(orden asc, _createdAt asc){\n  _id, empresa, cargo, fechaInicio, fechaFin, actual, bullets\n}': EXPERIENCIA_QUERY_RESULT;
    '*[_type == "habilidadGrupo"] | order(orden asc, _createdAt asc){\n  _id, nombreGrupo, habilidades\n}': HABILIDADES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
